/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class RTSPClientInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RTSPClientInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RTSPClientInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTSPModuleJNI.delete_RTSPClientInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RTSPClientInterface() {
    this(RTSPModuleJNI.new_RTSPClientInterface(), true);
  }

  public void SetFrameCallback(FrameCallback cb) {
    RTSPModuleJNI.RTSPClientInterface_SetFrameCallback(swigCPtr, this, FrameCallback.getCPtr(cb), cb);
  }

  public boolean Init() {
    return RTSPModuleJNI.RTSPClientInterface_Init(swigCPtr, this);
  }

}
